### ISSUE TITLE
#Fix 02 - Pagina Saque (Withdraw)  carregando por muito tempo

### ISSUE THREAD

**Issue by MuriloMamede** [LuizFilipeMoura/module1#4]
Pagina saque(withdraw), arquivo withdraw.js dentro da pasta /forex-nextjs/src/pages/  fica carregando por muito tempo quando não foi informado os dados bancários do usuário

**Comment by LuizFilipeMoura** [comment]
![image](https://user-images.githubusercontent.com/50964721/124180331-6cc31b80-da8a-11eb-8f8b-9ced374d8b21.png)

Uma possível solução seria mudar a ordem desse if que verifica se o usuário tem uma conta do banco fique antes dos outros, ou simplesmente buscar essa informação direto do context, que facilitaria e agilizaria o processo
