### ISSUE TITLE
#Fix 03 - Estilização da drawer

### ISSUE THREAD

**Issue by LuizFilipeMoura** [LuizFilipeMoura/module1#5]
A drawer-menu está sendo aberta do lado direito da tela, no canto oposto ao botão que a faz abrir. Seria mais amigável que ela abrisse do lado esquerdo

**Comment by MuriloMamede** [comment]
Para consertar isso basta alterar o valor "right" para "left" na linha 49 do arquivo Drawer.js, conforme a figura.

![image](https://user-images.githubusercontent.com/37355465/124181734-e9063080-da83-11eb-9304-211045e34b23.png)

**Comment by LuizFilipeMoura** [comment]
![image](https://user-images.githubusercontent.com/50964721/124186138-41442f00-da92-11eb-9132-717c858e1519.png)
Lembrando que nesse arquivo também temos referencia à ancora da drawer, que deve ser modificadas!

**Comment by Edu2804** [comment]
![image](https://user-images.githubusercontent.com/85701002/124186413-ab5cd400-da92-11eb-96bc-99697324b2d3.png)

Lembrando que nesse arquivo também temos referencia à ancora da drawer, que deve ser modificadas!

**Comment by helionardo** [comment]
![image](https://user-images.githubusercontent.com/62253035/124186297-1f46ae80-da8a-11eb-8dfd-fe72a43889f0.png)

Da forma como foi criada, está tendo um comportamento inesperado. Realize as devidas correções.
