### ISSUE TITLE
#Fix 04 - É necessário mudar a ordem desses tópicos.

### ISSUE THREAD

**Issue by Edu2804** [LuizFilipeMoura/module1#6]
![image](https://user-images.githubusercontent.com/85701002/124182019-b01e8980-da8c-11eb-93aa-0cf2631d6097.png)
-"History" deve estar no penúltimo tópico.
-"Send money" deve estar no terceiro tópico.
-"dashboard" deve estar no lugar do profile.

**Comment by LuizFilipeMoura** [comment]
Os labels e routes estão fora de ordem! Causando comportamentos inesperados

**Comment by MuriloMamede** [comment]
E os icons também, eles devem ser correspondentes
