### ISSUE TITLE
#Chore 01: Trocar os if-else por switch case

### ISSUE THREAD

**Issue by helionardo** [LuizFilipeMoura/module1#7]
Em 'globalFunctions', existem vários else-if, que podem ser trocados para um melhor entendimento, tornando o código mais legível.

**Comment by SantiagoMateus** [comment]
Na updatesWalletGlobal no primeiro if podemos fazer

switch (givenTransaction.from_currency) {
  case 'BRL':
    wallet.realamount += givenTransaction.from_amount;
  case 'USD':
    wallet.dollaramount += givenTransaction.from_amount;
  case 'GBP':
wallet.poundamount += givenTransaction.from_amount;
  case 'EUR':
wallet.euroamount += givenTransaction.from_amount;
  default:
    wallet;
}
